// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etwasycpohekfaoacffr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0d2FzeWNwb2hla2Zhb2FjZmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTU4NTQsImV4cCI6MjA2MzQ5MTg1NH0.3C0bT7rM3lrXVVMKWUuWSbNG3anHLAD3WdVIKJd7lI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);